image:
  - Visual Studio 2019

services:
  - mongodb

environment:
    CYG_MIRROR: http://cygwin.mirror.constant.com
    CYG_PACKAGES: make,unzip,automake,automake1.16,autoconf,autoconf2.5,zip,libbz2-devel,bzip2,xz,zlib,zlib-devel,python3,libtool,wget,liblzma-devel,libcurl-devel,R,libncurses-devel,python3-cython,python3-devel
    CYG_ROOT: C:\cygwin64
    CYG_CACHE: C:\cygwin64\var\cache\setup
    CYG_SETUP: setup-x86_64.exe
    BASH: C:\cygwin64\bin\bash
    CC: gcc
    PYTHON: "C:\\Python36"


# Cache Cygwin/MSYS files to speed up build
cache:
    - '%CYG_CACHE%'
clone_depth: 1

init:
  - git config --global core.autocrlf true

install:
  - set HOME=.
  - SET PATH=%PYTHON%;%PATH%
  - ps: if (Test-Path Env:\CYG_ROOT) { Start-FileDownload "https://cygwin.com/$env:CYG_SETUP" -FileName "$env:CYG_SETUP" }
  - '%CYG_SETUP% --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --packages "%CYG_PACKAGES%" --upgrade-also'
  - '%BASH% -lc "python3 -m ensurepip"'
  - '%BASH% -lc "pip3 install tox"'


build: off

test_script:
  - set HOME=.
  #- '%BASH% -lc "tox -e py3"'
  - '%BASH% -lc "echo skip tests to save time while testing pyinstaller"'

before_deploy:
  - set HOME=.
  - SET PATH=%PYTHON%;%PATH%
  #- '%BASH% -lc "git clone --recursive -b geno_kmer_count https://github.com/phelimb/mccortex"'
  #- '%BASH% -lc "cd mccortex/libs/htslib && git checkout bcf9bff178f81c9c1cf3a052aeb6cbe32fe5fdcc"'
  #- '%BASH% -lc "cd mccortex/libs/bcftools && git checkout b406a3906b153faa8bec0a53df07b2adf18a3052"'
  #- '%BASH% -lc "cd mccortex/libs/samtools && git checkout 2d4907cf9a34ccf7cde60143158b39e1cb40ac0c"'
  #- '%BASH% -lc "python3 ./ci/windows_xxhsum_fix.py"'
  #- '%BASH%  -lc "cd mccortex && make all && make tests"'
  #- python -m ensurepip
  #- python -m pip install pypiwin32 numpy==1.15
  #- python -m pip install pyinstaller
  #- python -m pip install .
  #- cd dist
  #- C:\Python36\Scripts\pyinstaller.exe --workpath=./pyinstaller_build/binary_cache --distpath=./pyinstaller_build mykrobe_atlas_pyinstaller.spec"
  #- cd ..
  #- '%BASH% -lc "ls -lh dist/pyinstaller_build/mykrobe_atlas/"'
  #- '%BASH% -lc "cd dist/pyinstaller_build && tar cvfz ../../mykrobe.command_line.windows.tar.gz mykrobe_atlas/"'


build_success:
  - '%BASH% -lc "echo TESTING123 > test.windows_deploy.txt"'

artifacts:
  - path: test.windows_deploy.txt
    type: File

deploy:
  provider: GitHub
  auth_token:
      secure: SOu4ZxY1S122CF3Fz52MvlZn9TMxtk14mPxFwy3TRCZhQFd3qGb/Gmwrfs7+0Hse
  artifact: test.windows_deploy.txt
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
