language: python
services: mongodb
cache: pip
sudo: required

jobs:
  include:
  - name: Ubuntu bionic Python 3.6
    os: linux
    dist: bionic
    python: '3.6'
    env: TOXENV=py36

  - name: OSX Python default version
    os: osx
    language: shell
    env:
    - TOXENV=py3
    before_install:
    - travis_wait 30 brew update
    - brew tap mongodb/brew
    - brew install mongodb-community
    - sudo mkdir -p /data/db
    - sudo chown -R `id -un` /data/db
    - mongod --quiet &>/dev/null &
    before_deploy:
    # We need to install mykrobe, including the data, so that when we run
    # pyinstaller later, it includes the data and the python module
    # dependencies
    # Also use sudo because otherwise anytree install failse when trying to
    # put a copy of its license into /usr/local/
    - sudo pip3 install .
    - mykrobe panels update_metadata --panels_dir src/mykrobe/data
    - mykrobe panels update_species --panels_dir src/mykrobe/data --debug all
    - pip3 install pyinstaller
    - cd dist
    - pyinstaller --workpath='./pyinstaller_build/binary_cache' --distpath='./pyinstaller_build' mykrobe_atlas_pyinstaller.spec
    - cd pyinstaller_build
    - tar cvfz ../../mykrobe.command_line.${TRAVIS_OS_NAME}.${TRAVIS_TAG}.tar.gz mykrobe_atlas/
    - cd ../../


install:
- pip3 install cython
- pip3 install requests
- travis_retry pip3 install tox
script: tox -e $TOXENV

deploy:
  provider: releases
  draft: true
  skip_cleanup: true
  api_key:
    secure: LaQUPzf9gvFicA9AAL3iLWKuZMxpXjjJaTLqD6vmBIuGnrvUDUvFU6DSpYKJktjUvM6XDyBJI7A/LCSiZ5+H25pfBPWU8XL41QiyAGG3oI9qWnnhEjtD/va49xf9la1d8ISfG+IMGLI7+n/G2tLCwhnouGLT4ntNnfMOeUQymgSPcyP3nc6ikoBq5SblMxXv9fpZvoSEah/wCDxak5r86dU2imPkH5TMLsdTaaVX4M+aTMqb38RqERFV7oQablHJ8Cwb4lMVO5WuYiLCyIjl1hf4yhQZAO8I2PcTETzDxvjsHZ5+FXidNB6zp66EYnyioS+ZwYopY3DO8Ri83WLyDA44TCzo84reOmwrMTeyrihdWXLM4yShRz1yLnFhJvXs4iZdFRt7eiQcnjeR3D8YLBtGMiTGSEl67gHpTl5aqgBL+xE2ESo9LZ1hC2ud+ff5avyPOQmfLGSKQSoMibU3KwvoYN+qmBEQiBAY9aTe4xTsd2NPY4qPD9Sr4PHed/jo7irUbx+RAQD43hGmswN60fwEEWpQ3UsU2J8mx0edywKxXFZ7IsotT8uwhOCbTZIVlWnXohKa/cEvnytOrKhtWo+afofQSokDWq7kBAGVP2aLmNmwY0ijMo+zKYOG3+jIsc4pWnDsuyNmIAQKFeB7lTZgC6COSykdPmZi8oI2rI8=
  file: mykrobe.command_line.${TRAVIS_OS_NAME}.${TRAVIS_TAG}.tar.gz
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx
    repo: Mykrobe-tools/mykrobe

notifications:
  email: false
